[window]
dimensions = { columns = 86, lines = 22 }
#position = { x = 504, y = 434 }
padding = { x = 10, y = 10 }
decorations = "full"
startup_mode = "Windowed"
opacity = 1.0

[scrolling]
history = 1000

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 10

[cursor]
style.shape = "Beam"
style.blinking = "On"

[selection]
save_to_clipboard = true


# Default colors
[colors.primary]
background = '#ffffe2'
foreground = '#000000'

dim_foreground = '#eff0f1'
bright_foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#f67400'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'
white = '#fcfcfc'

# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#31363b'
red = '#783228'
green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'


[terminal]
shell = { program = "zsh" }

[keyboard]
bindings = [
  { key = "Back", mods = "Alt", chars = "\u0008\u0008\u0008\u0008" },
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "M", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "PageUp", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "PageDown", mods = "Control|Shift", action = "SelectNextTab" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" }
]

[mouse]
hide_when_typing = false


